// Generated by CoffeeScript 1.9.3
(function() {
  var Twitter, querystring, request;

  querystring = require('querystring');

  request = require('request');

  Twitter = (function() {
    var toArray;

    Twitter.prototype.APIBase = 'https://api.twitter.com/1.1/';

    Twitter.prototype.streamBase = 'https://stream.twitter.com/1.1/';

    Twitter.prototype.uploadBase = 'http://upload.twitter.com/1.1/';

    toArray = function(args) {
      return Array.prototype.slice.call(args);
    };

    function Twitter(config) {
      this.config = config != null ? config : {};
      this.get = function() {
        return this.twitter.apply(this, [this.APIBase, 'GET'].concat(toArray(arguments)));
      };
      this.post = function() {
        return this.twitter.apply(this, [this.APIBase, 'POST'].concat(toArray(arguments)));
      };
      this.stream = function() {
        return this.twitter.apply(this, [this.streamBase].concat(toArray(arguments)));
      };
      this.stream.get = function() {
        return this.twitter.apply(this, [this.streamBase, 'GET'].concat(toArray(arguments)));
      };
      this.stream.post = function() {
        return this.twitter.apply(this, [this.streamBase, 'POST'].concat(toArray(arguments)));
      };
      this.upload = function() {
        return this.twitter.apply(this, [this.uploadBase].concat(toArray(arguments)));
      };
    }

    Twitter.prototype.twitter = function(baseUrl, method, account, resource, params, callback) {
      var paramString;
      paramString = querystring.stringify(params).replace(/\!/g, '%21').replace(/\'/g, '%27').replace(/\(/g, '%28').replace(/\)/g, '%29').replace(/\*/g, '%2A');
      return request({
        url: baseUrl + resource + '.json' + '?' + paramString,
        oauth: {
          consumer_key: this.config.oauth.consumer_key,
          consumer_secret: this.config.oauth.consumer_secret,
          token: this.config.oauth[account].oauth_token,
          token_secret: this.config.oauth[account].oauth_token_secret
        },
        json: true,
        method: method
      }, callback);
    };

    Twitter.prototype.formUpload = function(baseUrl, account, resource, formData, callback) {
      return request({
        url: baseUrl + resource + '.json',
        oauth: {
          consumer_key: this.config.oauth.consumer_key,
          consumer_secret: this.config.oauth.consumer_secret,
          token: this.config.oauth[account].oauth_token,
          token_secret: this.config.oauth[account].oauth_token_secret
        },
        json: true,
        method: 'POST',
        formData: formData
      }, callback);
    };

    return Twitter;

  })();

  module.exports = Twitter;

}).call(this);
